
spring:
  resources:
    static-locations: classpath:/templates/

# Nacos配置中心服务地址
nacos:
  config:
    server-addr: 114.116.26.35:8848
    data-id: shared_power_bank_web-dev.properties
    group: DEFAULT_GROUP
    type: properties
    bootstrap.enable: true
    enable-remote-sync-config: true
    namespace: 7f1093be-cc98-4dac-abd0-fd101bbf6de8


## Nacos服务管理中心
dubbo:
  application:
    name: shared_power_bank_web
  registry:
    address: nacos://127.0.0.1:8848
  consumer:
    timeout: 3000

users:
  service:
    version: 0.1.0


