
spring:
  resources:
    static-locations: classpath:/templates/

## Nacos服务管理中心
dubbo:
  application:
    name: shared_power_bank_web
  registry:
    address: nacos://wifi.stormbirds.cn:8848
  consumer:
    timeout: 3000

users:
  service:
    version: 0.1.0
equipment:
  service:
    version: 0.1.0


